### ISSUE TITLE
Settings tab has incorrect URL with namespaced classes

### ISSUE THREAD

**Issue by davejtoews** [jonom/silverstripe-someconfig#2]
For a namespaced class the href of the settings tab looks like.

`admin/someadmein/Fully-Namespaced-Class/EditForm/field/Fully\Namespaced\Class/item/1/edit`

but the URL it should be is

`admin/someadmein/Fully-Namespaced-Class/EditForm/field/Fully-Namespaced-Class/item/1/edit`

This should be resolved by #1

**Comment by davejtoews** [comment]
Resolved in [1.0.1](https://github.com/jonom/silverstripe-someconfig/releases/tag/1.0.1)

**Comment by lerni** [comment]
It still behaves wrong IMHO:
<video src="https://github.com/user-attachments/assets/8ffd52a7-8599-460a-9a43-76e272e8f987" controls width="100%"></video>

Not parsing the URL and using the first model feels better to me:
<video src="https://github.com/user-attachments/assets/4d34ff38-db53-4be5-9327-59ec30be0b5a" controls width="100%"></video>

**Comment by jonom** [comment]
@lerni sorry for the delay, I've been away on vacation. I'm surprised this isn't working as I was sure I tested all the back links. Would you mind posting the code from your example so I can verify the issue and the fix you submitted?

**Comment by lerni** [comment]
@jonom made it work with codespace but all in all it's slow and clunky. You may just take what you need from the repo. But check the [README.md](https://github.com/lerni/sc-bc/blob/master/README.md)
https://github.com/lerni/sc-bc/

**Comment by jonom** [comment]
Thanks @lerni, verified the issue using your code and merged your PR.
