### ISSUE TITLE
php81 Deprecated Calling static trait method

### ISSUE THREAD

**Issue by lerni** [jonom/silverstripe-someconfig#3]
`
[Deprecated] Calling static trait method JonoM\SomeConfig\SomeConfigAdmin::isConfig is deprecated, it should only be called on a class using the trait
jonom/silverstripe-someconfig/src/GridFieldDetailForm_ItemRequest_Extension.php:22
`

Update: Affects 81 not 80 - forgot to rebuild docker :see_no_evil:
https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.core.static-trait

**Comment by elliot-sawyer** [comment]
If you replace that line with `if(method_exists($class, 'current_config'))` instead (that's all `isConfig($class)` is doing), it should work.
